version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "15:00"
      timezon: "Europe/Helsinki"
    assignees: "jvnipers"
    commit-message:
      prefix: "npm"
