name: Prettier

on:
  push:
    branches: [misc-dev]
    paths-ignore:
      - LICENSE
      - README.md
      - .gitignore
      - ".github/*"
  pull_request:
    branches: [misc-dev]
    paths-ignore:
      - LICENSE
      - README.md
      - .gitignore
      - ".github/*"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run Prettier
        run: npx prettier --write .
